---
# Find a proper QEMU emulator
#
# Input:
#   item (required, usually defined inside loop)
#
# Output:
#   __tpa_vm_infra_emulator
#

- name: Run `command -v {{ item }}`
  ansible.builtin.shell: >-
    command -v {{ item }} || :
  args:
    executable: /usr/bin/bash
  register: __result
  changed_when: false
  when:
    - __tpa_vm_infra_emulator is undefined

- name: Store the result of `command -v {{ item }}` into the fact
  ansible.builtin.set_fact:
    __tpa_vm_infra_emulator: "{{ __result.stdout | trim }}"
  when:
    - __tpa_vm_infra_emulator is undefined
    - __result.stdout | trim | length > 0
