---
# Install tools for virtual machines maintenance
#
# Task variables:
#   vmtools_spec:
#     machines: A list of machines[1] (required)
#
#   [1] A minimal machine specification:
#     - name: A machine name (required)
#       network:
#         ipv4: A machine IPv4 address (required)
#

- name: Check that tools specification is defined
  ansible.builtin.assert:
    that:
      - vmtools_spec is defined
      - vmtools_spec is mapping
    fail_msg: >-
      `vmtools_spec` is not defined or it is not a mapping

- name: Check that `vmtools_spec.machines` is defined
  ansible.builtin.assert:
    that:
      - vmtools_spec.machines is defined
      - vmtools_spec.machines is sequence
    fail_msg: >-
      `vmtools_spec.machines` is not defined or it is not a list

- name: Check `vmtools_spec.machines` content
  ansible.builtin.assert:
    that:
      - item is mapping
      - item.name is defined
      - item.name is string
      - item.name | trim | length > 0
      - item.network is defined
      - item.network is mapping
      - item.network.ipv4 is defined
      - item.network.ipv4 is string
      - item.network.ipv4 | trim | length > 0
    fail_msg: >-
      `{{ item }}` must be a mapping containing `name` (a non-blank and
      non-empty string) and `network` (a mapping containing `ipv4` which must
      be a non-blank and non-empty string)
  loop: "{{ vmtools_spec.machines }}"

- name: Check that workspace is defined and it is a directory
  ansible.builtin.include_tasks:
    file: assert-workspace.yml

- name: Get SSH private key stats
  ansible.builtin.stat:
    path: "{{ rhtpa_vm_infra_workspace | trim }}/id_rsa"
  register: __result

- name: Check that SSH private key is an existing file
  ansible.builtin.assert:
    that:
      - __result.stat.isreg is defined
      - __result.stat.isreg

- name: Complete the tools specification
  ansible.builtin.set_fact:
    __vmtools_spec:
      topdir: "{{ role_path }}"
      user: "{{ __rhtpa_vm_infra_user }}"
      ssh_common_args: "{{ __rhtpa_vm_infra_ssh_common_args }}"
      id_rsa: "{{ rhtpa_vm_infra_workspace | trim }}/id_rsa"
      machines: "{{ vmtools_spec.machines }}"

- name: Print the tools specification
  ansible.builtin.debug:
    var: __vmtools_spec

- name: Compute the tools installation path
  ansible.builtin.set_fact:
    __home_local_bin_path: "{{ ansible_user_dir }}/.local/bin"

- name: Ensure the target directory exists
  ansible.builtin.file:
    path: "{{ __home_local_bin_path }}"
    state: directory
    mode: '0755'

- name: Install the tools shell script
  ansible.builtin.template:
    src: vmtools.j2
    dest: "{{ __home_local_bin_path }}/{{ __rhtpa_vm_infra_tools_sh }}"
    mode: '0755'

- name: Create symlinks
  ansible.builtin.file:
    src: "{{ __home_local_bin_path }}/{{ __rhtpa_vm_infra_tools_sh }}"
    dest: "{{ __home_local_bin_path }}/{{ item }}"
    state: link
  loop: "{{ __rhtpa_vm_infra_tools_sh_links }}"
