---
# Get `vm_spec.image` stats and store them to `__result`

- name: Check that `vm_spec.image` is defined
  ansible.builtin.assert:
    that:
      - vm_spec.image is defined
      - vm_spec.image is string
      - vm_spec.image | trim | length > 0
    fail_msg: >-
      `vm_spec.image` is not defined or it is not a string or it is blank or
      empty

- name: Get `vm_spec.image` stats
  ansible.builtin.stat:
    path: "{{
      (rhtpa_vm_infra_workspace | trim) + '/' + (vm_spec.image | trim) }}"
  register: __result
